# Generated by Django 5.0.7 on 2024-07-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_catagory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='item',
            name='subtitile',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
