# Generated by Django 5.0.7 on 2024-07-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_options_item_subtitile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='subtitile',
            field=models.CharField(max_length=100),
        ),
    ]
