# Generated by Django 5.0.7 on 2024-07-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_rename_subtitile_item_subtitle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('category',)},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
